# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 253bb7814cbca2d9d74663f05e0b4930352d693a7d8280540a2aba7a25beead4161e8666625da4c4fe5320d06cfda573be8b0d316aa9f674964c482fd31e691f

test:
  secret_key_base: c7fab0a5cbfc04f4ebbbf153e3f8de4b48f90ae98dc38ff99de96c550b295124945b1d58a6a0e71e58af7fcca52309bcf4e6a1d785f2e6ed4f817494b76bd189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
